name: haskell-restish
version: 0.1.0.0
github: "ogiles1999/haskell-restish"
license: BSD3
author: "oliver"
maintainer: "ogiles@email.com"
copyright: "2022 oliver"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/ogiles1999/haskell-restish#readme>

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  haskell-restish-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-restish
      - servant-server

tests:
  haskell-restish-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - haskell-restish
